clean up a couple of things causing tests to fail for me, and remove a feature that's not quite ready yet, and add another feature for innodb compression

diff --git a/bin/pt-mysql-summary b/bin/pt-mysql-summary
--- a/bin/pt-mysql-summary
+++ b/bin/pt-mysql-summary
@@ -700,20 +700,20 @@ has_symbols () {
 }
 
 setup_data_dir () {
-   local OPT_SAVE_DATA="$1"
+   local existing_dir="$1"
    local data_dir=""
-   if [ -z "$OPT_SAVE_DATA" ]; then
+   if [ -z "$existing_dir" ]; then
       mkdir "$TMPDIR/data" || die "Cannot mkdir $TMPDIR/data"
       data_dir="$TMPDIR/data"
    else
-      if [ ! -d "$OPT_SAVE_DATA" ]; then
-         mkdir "$OPT_SAVE_DATA" || die "Cannot mkdir $OPT_SAVE_DATA"
-      elif [ "$( ls "$OPT_SAVE_DATA" )" != "0" ]; then
+      if [ ! -d "$existing_dir" ]; then
+         mkdir "$existing_dir" || die "Cannot mkdir $existing_dir"
+      elif [ "$( ls -A "$existing_dir" )" ]; then
          die "--save-samples directory isn't empty, halting."
       fi
-      touch "$OPT_SAVE_DATA/test" || die "Cannot write to $OPT_SAVE_DATA"
-      rm "$OPT_SAVE_DATA/test"    || die "Cannot rm $OPT_SAVE_DATA/test"
-      data_dir="$OPT_SAVE_DATA"
+      touch "$existing_dir/test" || die "Cannot write to $existing_dir"
+      rm "$existing_dir/test"    || die "Cannot rm $existing_dir/test"
+      data_dir="$existing_dir"
    fi
    echo "$data_dir"
 }
