PT-2289 - Allow pt-stalk do disable ps-lock-transactions data collection via parameter
- Implemented feature
- Started working on the test

diff --git a/bin/pt-stalk b/bin/pt-stalk
--- a/bin/pt-stalk
+++ b/bin/pt-stalk
@@ -971,8 +971,10 @@ collect_mysql_data_one() {
       fi
    fi
 
-   $CMD_MYSQLADMIN $EXT_ARGV ext -i$OPT_SLEEP_COLLECT -c$cnt >>"$d/$p-mysqladmin" &
-   mysqladmin_pid=$!
+   if ! [ "${OPT_SKIP_COLLECTION}" =~ "mysqladmin" ]; then
+      $CMD_MYSQLADMIN $EXT_ARGV ext -i$OPT_SLEEP_COLLECT -c$cnt >>"$d/$p-mysqladmin" &
+      mysqladmin_pid=$!
+   fi
 
    ps_instrumentation_enabled=$($CMD_MYSQL $EXT_ARGV -e 'SELECT ENABLED FROM performance_schema.setup_instruments WHERE NAME = "transaction";' \
                                       | sed "2q;d" | sed 'y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/')
@@ -1014,18 +1016,25 @@ collect_system_data() {
 
 collect_mysql_data_loop() {
 
-
+   if ! [ "${OPT_SKIP_COLLECTION}" =~ "processlist" ]; then
       (echo $ts; $CMD_MYSQL $EXT_ARGV -e "SHOW FULL PROCESSLIST\G") \
       >> "$d/$p-processlist" &
-      (echo $ts; $CMD_MYSQL $EXT_ARGV -e "SELECT * FROM performance_schema.threads\G") \
-      >> "$d/$p-threads" &
-
-   if [ "$have_lock_waits_table" ]; then
-      (echo $ts; lock_waits "$d/lock_waits.running")   >>"$d/$p-lock-waits" &
-      (echo $ts; transactions) >>"$d/$p-transactions" &
    fi
 
-   if [ "${mysql_version}" '>' "5.6" ] && [ $ps_instrumentation_enabled == "yes" ]; then
+   (echo $ts; $CMD_MYSQL $EXT_ARGV -e "SELECT * FROM performance_schema.threads\G") \
+   >> "$d/$p-threads" &
+
+   if [ "$have_lock_waits_table" ]; then
+      if ! [ "${OPT_SKIP_COLLECTION}" =~ "lock-waits" ]; then
+         (echo $ts; lock_waits "$d/lock_waits.running")   >>"$d/$p-lock-waits" &
+      fi
+      if ! [ "${OPT_SKIP_COLLECTION}" =~ "transactions" ]; then
+         (echo $ts; transactions) >>"$d/$p-transactions" &
+      fi
+   fi
+
+   if [ "${mysql_version}" '>' "5.6" ] && [ $ps_instrumentation_enabled == "yes" ] \
+      && ! [ "${OPT_SKIP_COLLECTION}" =~ "ps-locks-transactions" ]; then
       ps_locks_transactions "$d/$p-ps-locks-transactions"
    fi
 
@@ -1252,20 +1261,22 @@ innodb_status() {
 
    local innostat=""
 
-   $CMD_MYSQL $EXT_ARGV -e "SHOW /*!40100 ENGINE*/ INNODB STATUS\G" \
-      >> "$d/$p-innodbstatus$n"
-   grep "END OF INNODB" "$d/$p-innodbstatus$n" >/dev/null || {
-      if [ -d /proc -a -d /proc/$mysqld_pid ]; then
-         for fd in /proc/$mysqld_pid/fd/*; do
-            file $fd | grep deleted >/dev/null && {
-               grep 'INNODB' $fd >/dev/null && {
-                  cat $fd > "$d/$p-innodbstatus$n"
-                  break
+   if ! [ "${OPT_SKIP_COLLECTION}" =~ "innodbstatus" ]; then
+      $CMD_MYSQL $EXT_ARGV -e "SHOW /*!40100 ENGINE*/ INNODB STATUS\G" \
+         >> "$d/$p-innodbstatus$n"
+      grep "END OF INNODB" "$d/$p-innodbstatus$n" >/dev/null || {
+         if [ -d /proc -a -d /proc/$mysqld_pid ]; then
+            for fd in /proc/$mysqld_pid/fd/*; do
+               file $fd | grep deleted >/dev/null && {
+                  grep 'INNODB' $fd >/dev/null && {
+                     cat $fd > "$d/$p-innodbstatus$n"
+                     break
+                  }
                }
-            }
-         done
-      fi
-   }
+            done
+         fi
+      }
+   fi
 }
 
 rocksdb_status() {
@@ -1274,7 +1285,7 @@ rocksdb_status() {
     has_rocksdb=`$CMD_MYSQL $EXT_ARGV -e "SHOW ENGINES" | grep -i 'rocksdb'`
     exit_code=$?
 
-    if [ $exit_code -eq 0 ]; then
+    if [ $exit_code -eq 0 ] && ! [ "${OPT_SKIP_COLLECTION}" =~ "rocksdbstatus" ]; then
         $CMD_MYSQL $EXT_ARGV -e "SHOW ENGINE ROCKSDB STATUS\G" \
                    >> "$d/$p-rocksdbstatus$n" || rm -f "$d/$p-rocksdbstatus$n"
     fi
@@ -1356,17 +1367,19 @@ collect_mysql_variables() {
    echo -e "\n$sql\n" >> $outfile
    $CMD_MYSQL $EXT_ARGV -e "$sql" >> $outfile
 
-   sql="select * from performance_schema.variables_by_thread order by thread_id, variable_name;"
-   echo -e "\n$sql\n" >> $outfile
-   $CMD_MYSQL $EXT_ARGV -e "$sql" >> $outfile
+   if ! [ "${OPT_SKIP_COLLECTION}" =~ "thread-variables" ]; then
+      sql="select * from performance_schema.variables_by_thread order by thread_id, variable_name;"
+      echo -e "\n$sql\n" >> $outfile
+      $CMD_MYSQL $EXT_ARGV -e "$sql" >> $outfile
 
-   sql="select * from performance_schema.user_variables_by_thread order by thread_id, variable_name;"
-   echo -e "\n$sql\n" >> $outfile
-   $CMD_MYSQL $EXT_ARGV -e "$sql" >> $outfile
+      sql="select * from performance_schema.user_variables_by_thread order by thread_id, variable_name;"
+      echo -e "\n$sql\n" >> $outfile
+      $CMD_MYSQL $EXT_ARGV -e "$sql" >> $outfile
 
-   sql="select * from performance_schema.status_by_thread order by thread_id, variable_name; "
-   echo -e "\n$sql\n" >> $outfile
-   $CMD_MYSQL $EXT_ARGV -e "$sql" >> $outfile
+      sql="select * from performance_schema.status_by_thread order by thread_id, variable_name; "
+      echo -e "\n$sql\n" >> $outfile
+      $CMD_MYSQL $EXT_ARGV -e "$sql" >> $outfile
+   fi
 
 }
 
@@ -1725,6 +1738,18 @@ main() {
 
    if [ "$OPT_SYSTEM_ONLY" ] && [ "$OPT_MYSQL_ONLY" ]; then
       log 'Both options --system-only and --mysql-only specified, collecting only disk-space, hostname, output, and trigger metrics';
+   fi
+
+   if [ "$OPT_SKIP_COLLECTION" ]; then
+      local supported_skips="ps-locks-transactions,thread-variables,innodbstatus,lock-waits,mysqladmin,processlist,rocksdbstatus,transactions"
+      IFS=',' read -ra skips <<< "$OPT_SKIP_COLLECTION"
+      for skip in "${skips[@]}"; do
+         echo "$supported_skips" | grep -q "$skip"
+         if [ $? -ne 0 ]; then
+            log "Invalid --skip-collection value: $skip, exiting."
+            exit 1
+         fi
+      done
    fi
 
    # Note: $$ is the parent's PID, but we're a child proc.
@@ -2390,6 +2415,12 @@ type: int; default: 1
 How long to sleep between collection loop cycles.  This is useful with
 C<--no-stalk> to do long collections.  For example, to collect data every
 minute for an hour, specify: C<--no-stalk --run-time 3600 --sleep-collect 60>.
+
+=item --skip-collection
+
+type: array
+
+A comma-separated list of collection types to skip.  Valid values are: C<"ps-locks-transactions,thread-variables,innodbstatus,lock-waits,mysqladmin,processlist,rocksdbstatus,transactions">.
 
 =item --socket
 
