Wait 1 minute to start and stop sandboxes.  Report how long start/stop took.  Clean up code.

diff --git a/sandbox/start-sandbox b/sandbox/start-sandbox
--- a/sandbox/start-sandbox
+++ b/sandbox/start-sandbox
@@ -1,8 +1,13 @@
 #!/bin/sh
 
-# This script makes Maatkit sandbox servers for mk-test-env.
-# It's a "low level" script that is not usually called directly.
-# Exit 0 means everything was successful, else exit 1 on problems.
+# This script starts a Percona Toolkit sandbox sever.  sandbox/test-env
+# uses it, and many tests use it to create special, temporary sandbox
+# servers.  The actual startup is done by /tmp/PORT/start, which this
+# script calls after doing a bunch of sanity checks.
+#
+# Exit 0 if the sandbox server started ok, else 1 and debug_sandbox()
+# is caleld to print some info to STDERR about what state the sandbox
+# server might have been in.
 
 die() {
    echo $1 >&2
@@ -10,16 +15,12 @@ die() {
 }
 
 debug_sandbox() {
+   set -x
    local port="$1"
-   echo
-   echo "MySQL processes:" >&2
    ps x | grep mysql >&2
-   echo
    if [ -d "/tmp/$port" ]; then
       ls -lh /tmp/$port/* >&2
-      echo
       cat /tmp/$port/data/mysqld.log >&2
-      echo
       tail -n 100 /tmp/$port/data/genlog >&2
    else
       echo "/tmp/$port does not exist" >&2
@@ -28,8 +29,8 @@ debug_sandbox() {
 
 make_sandbox() {
    # Make the sandbox dir and extract the base files.
-   rm -rf /tmp/$port || die "can't rm /tmp/$port"
-   mkdir /tmp/$port || die "mkdir /tmp/$port failed"
+   rm -rf /tmp/$port || die "Failed to rm /tmp/$port"
+   mkdir /tmp/$port  || die "Failed to mkdir /tmp/$port"
    cp $PERCONA_TOOLKIT_BRANCH/sandbox/servers/$version/my.sandbox.cnf /tmp/$port
    tar xzf $PERCONA_TOOLKIT_BRANCH/sandbox/servers/$version/data.tar.gz -C /tmp/$port
 
@@ -84,7 +85,7 @@ make_sandbox() {
          /tmp/$port/use -e 'SHOW /*!40100 ENGINE*/ INNODB STATUS' | grep 'INNODB MONITOR OUTPUT' >/dev/null 2>&1
          # grep exits 0 if lines are found
          if [ $? -ne 0 ]; then
-            echo "Sandbox $type $port doesn't have InnoDB" >&2
+            echo "Sandbox $type $port doesn't have InnoDB." >&2
             debug_sandbox $port
             exit 1
          fi
@@ -146,7 +147,7 @@ fi
 
 cd $PERCONA_TOOLKIT_BRANCH/sandbox
 
-# This script is usually called by mk-test-env which discovers and
+# This script is usually called by test-env which discovers and
 # sets PERCONA_TOOLKIT_SANDBOX.  If this script is called directly,
 # then the caller is reponsible for setting PERCONA_TOOLKIT_SANDBOX.
 # PERCONA_TOOLKIT_SANDBOX points to a base directory containing the
