Report when a /tmp/port is missing files.

diff --git a/sandbox/stop-sandbox b/sandbox/stop-sandbox
--- a/sandbox/stop-sandbox
+++ b/sandbox/stop-sandbox
@@ -20,6 +20,9 @@ for port in "$@"; do
    if [ -x "/tmp/$port/stop" ]; then
       /tmp/$port/stop
       exit_status=$((exit_status | $?))
+   else
+      echo "/tmp/$port is missing files:" >&2
+      ls -la /tmp/$port >&2
    fi
 
    rm -rf /tmp/$port
