Remove "internal" bugs from Changelog. Make build-packages write simple version and update sphinx-build/conf.py.  Make write-user-docs remove double blank lines.  Remove pt-checksum-filter and other removed tools from user docs.

diff --git a/util/build-packages b/util/build-packages
--- a/util/build-packages
+++ b/util/build-packages
@@ -65,6 +65,7 @@ cd $cwd
 # ############################################################################
 
 DOCS_DIR=$BRANCH/docs
+SPHINX_CONFIG_DIR=$BRANCH/config/sphinx-build
 DEB_CONFIG_DIR=$BRANCH/config/deb
 RPM_CONFIG_DIR=$BRANCH/config/rpm
 RELEASE_DIR=$BRANCH/release
@@ -123,19 +124,16 @@ check_rel_notes() {
 update_version() {
    echo -n "Updating version in tools... "
    cd $BRANCH/bin
-
-   local new_version_str="Percona Toolkit v$VERSION released $DATE"
-
    for tool_file in *; do
-      sed -i'.bak' -e "s/^Percona Toolkit v.*/$new_version_str/" $tool_file
+      sed -i'.bak' -e "s/^$tool [0-9]\./$tool $VERSION/" $tool_file
       if [ $? -ne 0 ]; then
          die "Error updating version in $tool_file"
       fi
       rm "$tool_file.bak"
    done
 
-   local new_versions=$(grep --no-filename '^Percona Toolkit v' * | sort -u)
-   if [ "$new_versions" != "$new_version_str" ]; then
+   local new_versions=$(grep --no-filename '^pt-[^ ]\+ [0-9]\.' * | cut -d' ' -f2 | sort -u)
+   if [ "$new_versions" != "$VERSION" ]; then
       die "The version in some tool did not update correctly"
    fi
    echo "OK"
@@ -151,11 +149,27 @@ update_version() {
    
    echo -n "Updating version in percona-toolkit.pod... "
    cd $DOCS_DIR
-   sed -i'.bak' -e "s/^Percona Toolkit v.*/$new_version_str/" percona-toolkit.pod
+   sed -i'.bak' -e "s/^Percona Toolkit v.*/Percona Toolkit v$VERSION released $DATE/" percona-toolkit.pod
    if [ $? -ne 0 ]; then
       die "Error updating version in percona-toolkit.pod"
    fi
    rm "percona-toolkit.pod.bak"
+   echo "OK"   
+   
+   echo -n "Updating version in sphinx-build/conf.py... "
+   # What Sphinx calls verison, we call series; what it calls release we
+   # call version.
+   cd $SPHINX_CONFIG_DIR
+   sed -i'.bak' -e "s/^version =/version = '$SERIES'/" conf.py
+   if [ $? -ne 0 ]; then
+      die "Error updating version in conf.py"
+   fi
+   rm "conf.py.bak"
+   sed -i'.bak' -e "s/^release =/version = '$VERSION'/" conf.py
+   if [ $? -ne 0 ]; then
+      die "Error updating release in conf.py"
+   fi
+   rm "conf.py.bak"
    echo "OK"   
 }
 
@@ -414,6 +428,7 @@ fi
 # Setting LANG as such works for me; hopefully it works for you, too.
 LANG='en_US.UTF-8'
 
+SERIES=$(echo $VERISON | sed 's/\.[0-9][0-9]*$//')
 YEAR=$(date -u +'%Y')                      # for updating copyright year
 DATE=$(date -u +'%F')                      # for updating release date
 DEB_DATE=$(date -u +'%a, %d %b %Y %T %z')  # for updating deb/changelog
